//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherControl.Enlace_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int IdCalificacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdSemestre { get; set; }
        public int IdAsignatura { get; set; }
        public int IdSeccion { get; set; }
        public int IdEvaluacion { get; set; }
    }
}
