//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegEstudiantes.Enlace_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccione
    {
        public int IdSeccion { get; set; }
        public int Numero { get; set; }
        public int IdAsignatura { get; set; }
        public int IdProfesor { get; set; }
        public string Aula { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
        public Nullable<bool> Activa { get; set; }
    }
}
